networks:
  default:
    external: true
    name: ${DOCKER_MY_NETWORK}
services:
  homebox:
    container_name: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest
    restart: unless-stopped
    volumes:
      - ${DOCKER_HOME}/homebox/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      TZ: ${TZ}
      HBOX_OPTIONS_ALLOW_REGISTRATION: false
    # ports:
    #   - '7745:7745'
    networks:
      default:
        ipv4_address: 172.20.0.40
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
