networks:
  default:
    external: true
    name: ${DOCKER_MY_NETWORK}
services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    container_name: dozzle
    #ports:
    # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKER_HOME}/dozzle/data:/data
    networks:
      default:
        ipv4_address: 172.20.0.38
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 4h
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M

