networks:
  default:
    external: true
    name: ${DOCKER_MY_NETWORK}
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_HOME}/portainer/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # ports:
    #   - "9000:9000"
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.3
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
