networks:
  default:
    external: true
    name: ${DOCKER_MY_NETWORK}
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
    command: ["--loglevel warning"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      # - ${DOCKER_HOME}/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ${DOCKER_HOME}/redis/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      default:
        ipv4_address: 172.20.0.31
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
